### ISSUE TITLE
Email Address Missing From OpenStack Invoice CSV

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/openstack-billing-from-db#27]
## Motivation
In December this project `05cca114ea014b8ea588016e9d2aff04` had no Manager (PI) associated with it. It was also archived during the month. We want to know why the email address was missing and make sure in future versions of the script we retain the email address.

## Completion Criteria
The script includes Manager (PI) field for all projects

## Description
- [ ] Test why the Manager (PI) was missing, the current theory is archiving of project
- [ ] Update script to include the email address for all projects

## Completion dates
Desired - 2024-01-10
Required - TBD

**Comment by knikolla** [comment]
The email address was missing because someone manually deleted the attribute `Allocated Project ID` on the Resource Allocation. Without that attribute the invoicing scripts are unable to match the OpenStack/OpenShift project to the ColdFront Resource Allocation and therefore cannot look up PI information. 

Archival is not a problem, I am able to look up information for archived Projects and Allocations from the API.

Please don't manually delete attributes in ColdFront if you don't know what you're doing.
